import mongoose from 'mongoose';

// The raw deviceId is a random secret generated by the app; only its hash is stored.
const deviceSchema = new mongoose.Schema(
  {
    userId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true, index: true },
    deviceHash: { type: String, required: true },
    name: { type: String, default: 'Unknown device', maxlength: 80 },
    trusted: { type: Boolean, default: false },
    firstSeen: { type: Date, default: Date.now },
    lastSeen: { type: Date, default: Date.now },
    lastIp: String,
  },
  { timestamps: true }
);

deviceSchema.index({ userId: 1, deviceHash: 1 }, { unique: true });

export default mongoose.model('Device', deviceSchema);
